"use client";

import * as React from "react";
import Link from "next/link";
import { Sparkles, AlertTriangle } from "lucide-react";

import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { useAuth } from "@/lib/auth-context";

type InsightsResponse = {
  configured: boolean;
  insight: string | null;
  error: string | null;
};

export function AiInsightsCard() {
  const { token } = useAuth();
  const [loading, setLoading] = React.useState(false);
  const [result, setResult] = React.useState<InsightsResponse | null>(null);
  const [requestError, setRequestError] = React.useState<string | null>(null);

  async function handleGenerate() {
    setLoading(true);
    setRequestError(null);

    try {
      const res = await fetch(
        `${process.env.NEXT_PUBLIC_API_URL}/analytics/ai-insights`,
        {
          method: "POST",
          headers: {
            ...(token ? { Authorization: `Bearer ${token}` } : {}),
          },
        }
      );

      const body = await res.json().catch(() => null);

      if (!res.ok) {
        throw new Error(body?.message ?? `Request failed with status ${res.status}`);
      }

      setResult(body);
    } catch (err) {
      setRequestError(
        err instanceof Error ? err.message : "Could not generate insights."
      );
    } finally {
      setLoading(false);
    }
  }

  return (
    <Card>
      <CardHeader className="flex-row items-center justify-between gap-4 space-y-0">
        <div>
          <CardTitle className="flex items-center gap-2">
            <Sparkles className="h-4 w-4 text-muted-foreground" />
            AI Insights
          </CardTitle>
          <CardDescription className="mt-1">
            A short written summary of the last 90 days, generated by your configured AI provider.
          </CardDescription>
        </div>
        <Button
          type="button"
          size="sm"
          onClick={handleGenerate}
          disabled={loading}
        >
          {loading ? "Generating…" : "Generate AI Insights"}
        </Button>
      </CardHeader>
      <CardContent>
        {requestError && (
          <div className="flex items-start gap-2 rounded-lg border border-destructive/20 bg-destructive/10 px-3 py-2 text-sm text-destructive">
            <AlertTriangle className="mt-0.5 h-4 w-4 shrink-0" />
            <span>{requestError}</span>
          </div>
        )}

        {result && result.configured === false && (
          <p className="text-sm text-muted-foreground">
            AI insights aren&apos;t configured yet. Add an API key in{" "}
            <Link
              href="/dashboard/settings"
              className="underline underline-offset-2"
            >
              Settings &gt; AI
            </Link>
            .
          </p>
        )}

        {result && result.configured && result.error && (
          <div className="flex items-start gap-2 rounded-lg border border-destructive/20 bg-destructive/10 px-3 py-2 text-sm text-destructive">
            <AlertTriangle className="mt-0.5 h-4 w-4 shrink-0" />
            <span>{result.error}</span>
          </div>
        )}

        {result && result.configured && result.insight && (
          <p className="whitespace-pre-line text-sm text-foreground">
            {result.insight}
          </p>
        )}

        {!result && !requestError && (
          <p className="text-sm text-muted-foreground">
            Click &quot;Generate AI Insights&quot; for a written summary of
            recent performance and suggestions.
          </p>
        )}
      </CardContent>
    </Card>
  );
}

export default AiInsightsCard;
